### ISSUE TITLE
Question: DRM Whilst X11 is Running?

### ISSUE THREAD

**Issue by stevenlovegrove** [aritger/eglstreams-kms-example#3]
This code is fantastic and works great after shutting down X11 as you intended, but I was wondering what the specific limitations may be for future implementations?

Given a machine with one Titan X graphics card connected to two monitors, for example, is there a way to use X11 on one monitor, and use this drm kms method to render directly to the other?

If not, do you know of any other way to get low-latency, low-overhead rendering to one display on Linux whilst keeping a standard Ubuntu desktop up on the other?

**Comment by aritger** [comment]
Thanks for your interest, Steven.  Unfortunately, right now, only one of X or EGLStreams could use a GPU at a time.

Longer term, for the use case you describe, the "Presenting Directly to Display Devices" portion of the Vulkan Window System Integration (WSI) specification may be interesting:

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#display

Though, NVIDIA doesn't support that, yet...
